project_name: replay-stream
project_description: node.js stream to filter or replay items based on timestamp
project_url: https://github.com/ornl-situ/replay-stream

team_name: The Situational Understanding Research Team
team_url: https://github.com/ornl-situ

org_name: Oak Ridge National Laboratory
org_url: https://www.ornl.gov/
    
pygments: true
markdown: rdiscount